# TODO: finish this

FROM python:3.12-slim-bookworm

WORKDIR /app 

RUN pip install --upgrade pip && pip install uv 

COPY . /app

RUN uv lock && uv sync --all-extras

CMD ["gateway", "start", "community"]